# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: make build
  
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    services:
      docker:
        image: docker:20.10.7
        options: --privileged # Required for Docker-in-Docker
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Set up Docker Buildx for test containers
      uses: docker/setup-buildx-action@v1
  
    - name: Test
      run: make test
